### PR TITLE
adds log_level setting to bot configuration

### PR DESCRIPTION
**Pull request by TheNotary**
Addresses #229 but there's no Gemfile and 5 tests are failing for me on master, so it's unclear if 100% of the required patches have been made.

### CODE REVIEW

**Comment by dominikh** [comment]
Don't bother with the tests, they're awful and incomplete. You will, however, want to document the new option in `docs/bot_options.md` – While doing so, it should be made clear that the option only applies to the default logger, not other loggers that are added manually to the list of loggers.

**Comment by TheNotary** [comment]
Good catch, I had a tiny bit of cognitive dissonance as I picked the original name for the config value.  Does it seem to be working on your end?

**Comment by bougyman** [comment]
Will test this tomorrow.

**Comment by kuzmik** [comment]
Can we get this merged? I'd love to start filtering logs!

**Pull request merged**
